import os
import math

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

def define(name, value):
    return f"#define {name} {value}"

def generate_c_table(
    name, size, func, c_type="int", fmt="{:d}", const=True, static=True, per_line=8, section=None
):
    """
    Generate a C array definition for a lookup table.

    Args:
        name (str): Name of the array.
        size (int): Number of elements.
        func (callable): Function taking index (int) and returning value.
        c_type (str): C type of the array elements.
        fmt (str): Format string for each value (e.g. "{:d}", "{:.6f}").
        const (bool): If True, add 'const'.
        static (bool): If True, add 'static'.
        per_line (int): Number of elements per line.
        section (str or None): If set, add GCC section attribute (e.g. ".rodata").

    Returns:
        str: C code for the array.
    """
    qualifiers = []
    if static:
        qualifiers.append("static")
    if const:
        qualifiers.append("const")
    qualifiers = " ".join(qualifiers)
    section_attr = f' __attribute__((section("{section}")))' if section else ""
    lines = [f"{qualifiers} {c_type} {name}[{size}]{section_attr} = {{"]
    row = []
    for i in range(size):
        value = func(i)
        row.append(fmt.format(value))
        if (i + 1) % per_line == 0 or i == size - 1:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    return "\n".join(lines)

def write_c_header(segments, path, includes=None):
    lines = [
        "// This file is auto-generated by scripts/bake.py. Do not edit manually.",
        "",
        "#pragma once",
        "",
        "",
    ]

    if includes:
        for include in includes:
            if not include.startswith("<"):
                include = f'"{include}"'
            lines.append(f'#include {include}')
        lines.append("")
        lines.append("")


    for segment in segments:
        lines.append(segment)
        lines.append("")

    with open(os.path.join(PROJECT_ROOT, path), "w") as f:
        f.write("\n".join(lines))


def note_dphase_lut(size=128):
    a4_freq = 440.0
    sample_rate = 48000.0
    def note_to_dphase(note):
        frequency = math.pow(2, (note - 69) / 12) * a4_freq
        return int((frequency / sample_rate) * (1 << 32))  # Convert to fixed-point dphase


    table = generate_c_table(
        "NOTE_DPHASE_LUT", size, note_to_dphase, c_type="uint32_t", fmt="{:d}", section=".rodata"
    )
    write_c_header([
        define("NOTE_DPHASE_LUT_SIZE", size),
        define("NOTE_DPHASE_LUT_SAMPLE_RATE", sample_rate),
        table
    ], "build/note_dphase_lut.h", includes=["<stdint.h>"])


if __name__ == "__main__":
    note_dphase_lut()
