#!/bin/bash
set -euo pipefail

# fix cwd
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR/.."

shopt -s nullglob

ASEPRITE_CLI="$HOME/Library/Application Support/Steam/steamapps/common/Aseprite/Aseprite.app/Contents/MacOS/aseprite"

for dir in src/shared/apps/*; do
  [ -d "$dir/assets" ] || continue
  echo "processing $dir..."
  assets_path="$dir/assets.h"

  {
    echo "// auto-generated image assets"
    echo "// generated by /scripts/export.sh"
    echo "#pragma once"
    echo "#include <stdint.h>"
    echo
  } > "$assets_path"
  
  for file in "$dir/assets"/*.aseprite; do
    [ -e "$file" ] || continue
    "$ASEPRITE_CLI" \
      -b \
      "$file" \
      --save-as "$dir/assets/$(basename "$file" .aseprite)_{tag}_{frame}.bmp"
  done

  for file in "$dir/assets"/*.bmp; do
    [ -e "$file" ] || continue

    name=$(basename "$file" .bmp)
    varname="${name//[^a-zA-Z0-9_]/_}"
    echo "  exporting $varname"

    xbm_path="$dir/assets/$varname.xbm"
    magick "$file" -monochrome -negate "$xbm_path"
    sed 's/static char/static const uint8_t/' "$xbm_path" >> "$assets_path"
    echo "" >> "$assets_path"
  done

  rm -r "$dir/assets/"*.{bmp,xbm}
done
