import argparse
import atexit
import os
import subprocess
import sys
import time
from pathlib import Path
from typing import List

DEFAULT_REAPER_PATH = r"C:\Program Files\REAPER (x64)\reaper.exe"
REASCRIPT_PATH = Path(__file__).resolve().with_name("rea_midi_export.lua")

subprocs: List[subprocess.Popen] = []
atexit.register(lambda: [p.kill() for p in subprocs if p.poll() is None])


def write_text_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def sanitize_symbol(raw: str) -> str:
    out = []
    for ch in raw:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    symbol = "".join(out).strip("_")
    if not symbol:
        symbol = "song"
    if symbol[0].isdigit():
        symbol = f"song_{symbol}"
    return symbol


def emit_midi_header(symbol: str, source_rpp: str, midi_bytes: bytes) -> str:
    lines = [
        "// Auto-generated by scripts/rea_midi_export.py. Do not edit.",
        f"// Source: {source_rpp}",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
    ]

    lines.append(f"#define {symbol.upper()}_MIDI_LEN {len(midi_bytes)}u")
    lines.append("")
    lines.append(f"static const uint8_t {symbol}_midi[{len(midi_bytes)}] = {{")

    row = []
    for i, b in enumerate(midi_bytes):
        row.append(f"0x{b:02X}")
        if len(row) >= 16 or i == len(midi_bytes) - 1:
            lines.append("  " + ", ".join(row) + ",")
            row = []

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def build_header_from_midi(
    rpp_path: str, midi_path: Path, header_out: Path, symbol: str
) -> None:
    midi_bytes = midi_path.read_bytes()
    content = emit_midi_header(symbol, rpp_path, midi_bytes)
    write_text_if_changed(header_out, content)
    print(f"Generated MIDI header: {header_out}")


def run_export(rpp_path: Path, midi_out_path: Path, reaper_path: str) -> bool:
    midi_out_path.parent.mkdir(parents=True, exist_ok=True)
    prev_mtime = midi_out_path.stat().st_mtime if midi_out_path.exists() else None

    env = dict(os.environ)
    env["REAPER_EXPORT_MIDI_PATH"] = str(midi_out_path)

    proc = subprocess.Popen(
        [
            reaper_path,
            "-newinst",
            "-nosplash",
            str(rpp_path),
            str(REASCRIPT_PATH),
        ],
        env=env,
    )
    subprocs.append(proc)

    while proc.poll() is None:
        mtime = midi_out_path.stat().st_mtime if midi_out_path.exists() else None
        if mtime is not None and mtime != prev_mtime:
            while True:
                time.sleep(0.1)
                m2 = midi_out_path.stat().st_mtime if midi_out_path.exists() else None
                if m2 == mtime:
                    break
                mtime = m2
            print(f"Exported MIDI: {midi_out_path}")
            proc.kill()
            return True
        time.sleep(0.5)

    print("Error: REAPER process exited without exporting MIDI.")
    return False


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export REAPER RPP to MIDI and optionally generate a C header with raw MIDI bytes"
    )
    parser.add_argument(
        "legacy_rpp", nargs="?", help="Backward-compatible positional RPP path"
    )
    parser.add_argument("--rpp", help="Input .rpp project file")
    parser.add_argument("--midi-out", help="Output MIDI file path (.mid)")
    parser.add_argument("--header-out", help="Output C header path (.h)")
    parser.add_argument("--symbol", help="Base C symbol for generated data")
    parser.add_argument(
        "--reaper-path",
        default=os.environ.get("REAPER_PATH", DEFAULT_REAPER_PATH),
        help="Path to REAPER executable",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    rpp_raw = args.rpp or args.legacy_rpp
    if not rpp_raw:
        print(
            "Error: provide --rpp <path> (or legacy positional path).", file=sys.stderr
        )
        return 2

    rpp_path = Path(rpp_raw).resolve()
    if not rpp_path.is_file():
        print(f"Error: {rpp_path} is not a valid file.", file=sys.stderr)
        return 2

    midi_out = (
        Path(args.midi_out).resolve() if args.midi_out else rpp_path.with_suffix(".mid")
    )

    reaper_path = Path(args.reaper_path)
    if not reaper_path.exists():
        print(f"Error: REAPER not found at: {args.reaper_path}", file=sys.stderr)
        return 2

    if not run_export(rpp_path, midi_out, args.reaper_path):
        return 1

    if args.header_out:
        symbol = sanitize_symbol(args.symbol or ("sounds_" + rpp_path.stem))
        relative_rpp = str(rpp_path.relative_to(Path(__file__).parent.parent)).replace(
            "\\", "/"
        )
        build_header_from_midi(
            relative_rpp, midi_out, Path(args.header_out).resolve(), symbol
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
