#pragma once

#include <stdint.h>

#define PRISM_DISPLAY_WIDTH 128
#define PRISM_DISPLAY_HEIGHT 64

#define DISP_WIDTH PRISM_DISPLAY_WIDTH
#define DISP_HEIGHT PRISM_DISPLAY_HEIGHT

static const uint32_t PRISM_DISPLAY_PIXELS =
    PRISM_DISPLAY_WIDTH * PRISM_DISPLAY_HEIGHT;

